// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pno8A8SYEQICyQ8JSlA-SyUYT-q7qSk',
    appId: '1:862480204476:web:183bddf2521e35484ac6b9',
    messagingSenderId: '862480204476',
    projectId: 'nutcai-agents',
    authDomain: 'nutcai-agents.firebaseapp.com',
    storageBucket: 'nutcai-agents.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0sAE6NTqZYXoQlnKee0BH2PTrB6Hg0S8',
    appId: '1:862480204476:android:9245455bd5b4abc74ac6b9',
    messagingSenderId: '862480204476',
    projectId: 'nutcai-agents',
    storageBucket: 'nutcai-agents.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-sWFdaWJvAN7EIx-7XFM-iTCEwZunvn0',
    appId: '1:862480204476:ios:aaf77e36daafb8ba4ac6b9',
    messagingSenderId: '862480204476',
    projectId: 'nutcai-agents',
    storageBucket: 'nutcai-agents.firebasestorage.app',
    iosBundleId: 'com.example.nutricareAgents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-sWFdaWJvAN7EIx-7XFM-iTCEwZunvn0',
    appId: '1:862480204476:ios:aaf77e36daafb8ba4ac6b9',
    messagingSenderId: '862480204476',
    projectId: 'nutcai-agents',
    storageBucket: 'nutcai-agents.firebasestorage.app',
    iosBundleId: 'com.example.nutricareAgents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0pno8A8SYEQICyQ8JSlA-SyUYT-q7qSk',
    appId: '1:862480204476:web:76bf57bd5c49e4274ac6b9',
    messagingSenderId: '862480204476',
    projectId: 'nutcai-agents',
    authDomain: 'nutcai-agents.firebaseapp.com',
    storageBucket: 'nutcai-agents.firebasestorage.app',
  );
}
